version: "3.2"
services:
  backend:
    build: ./docker/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - redis
    entrypoint: ["/bin/bash", "-c", "/missionaryfamily777/docker/backend/start_api.sh"]
  redis:
    image: redis
    ports:
      - "6379:6379"

  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #     # One-way volume to use node_modules from inside image
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - backend
  #   command: npm start